 name: sync-common-types-files
 on: 
   push:
     branches:
       - main
     paths: 
       - 'specification/common-types/**'
   schedule:
       - cron: '0 8 * * *'
       - cron: '*/15 * * * *'
   workflow_dispatch:
 jobs:
   sync-files-RPSaaSMaster:
     name: sync-files-RPSaaSMaster
     if: ${{ github.repository != 'test-repo-billy/azure-rest-api-specs' }}
     runs-on: ubuntu-latest
     steps:
       - name: checkoutV2 
         uses: actions/checkout@v2
       - name: sync-common-types-files
         uses: ./
         with:
            SOURCE: test-repo-billy/azure-rest-api-specs-pr@main
            DEST: test-repo-billy/azure-rest-api-specs-pr@RPSaaSMaster
            FILE_PATH: specification/common-types
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
   sync-files-RPSaaSDev:
     name: sync-files-RPSaaSDev
     if: ${{ github.repository != 'test-repo-billy/azure-rest-api-specs' }}
     runs-on: ubuntu-latest
     steps:
       - name: checkoutV2 
         uses: actions/checkout@v2
       - name: sync-common-types-files
         uses: ./
         with:
            SOURCE: test-repo-billy/azure-rest-api-specs-pr@main
            DEST: test-repo-billy/azure-rest-api-specs-pr@RPSaaSDev
            FILE_PATH: specification/common-types
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
